[[session]]
name = "API"
path = "~/projects/ncl-api"
startup_command = "~/.dotfiles/config/tmux/scripts/split-window.sh"

[[session]]
name = "Synergy"
path = "~/projects/synergy-spa"
startup_command = "~/.dotfiles/config/tmux/scripts/split-window.sh"

[[session]]
name = "Dotfiles"
path = "~/.dotfiles"
startup_command = "~/.dotfiles/config/tmux/scripts/split-window.sh"
